# Workshop 2
Part of this tutorial is based on the NumPy and Matplotlib documentation (https://numpy.org/doc/stable/ and https://matplotlib.org/stable/contents.html). Also, part of this tutorial is based on the Python introduction from last year of André Jüling, created under the BSD 3-Clause License (https://github.com/AJueling/python_climate_physics).

In this workshop we will pay attention to Python the packages NumPy (Numerical Python), Matplotlib (Mathematical p
Plotting Library). The standard Python library is deliberately kept small, because there are so many different use cases, scientific computing is just one of them.
Importing packages brings new variables (mostly functions) into our interpreter which allows us to extend functionality with code written by the community. There are many more packages (freely and openly) available, which you can use to do different things. In the next tutorials, we will work with packages that for example can import and analyze data and other packages that can our plots look nicer. However, the NumPy and Matplotlib packages are two of the most fundamental parts of the scientific Python "ecosystem". Most of everything else is built on top of them which is why we cover them first (see Figure below).

<img src="https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2649-2/MediaObjects/41586_2020_2649_Fig2_HTML.png" width="600">
(Figure 2 of the Numpy review article (doi:10.1038/s41586-020-2649-2))


## 1. NumPy
At the core of the NumPy package, is the `ndarray` object. These are $n$-dimensional arrays of homogeneous data types, for which a lot of methods (=functions) are built-in. With NumPy arrays you can do advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. This is useful, because size and speed matter when we are dealing with large and complex data or models. Some examples of what you can do with NumPy is depicted in the figure below.

<img src="https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2649-2/MediaObjects/41586_2020_2649_Fig1_HTML.png" width="900">

Figure 1 of the NumPy review article (doi:10.1038/s41586-020-2649-2) with its caption:

__a__ The NumPy array data structure and its associated metadata fields. 

__b__ Indexing an array with slices and steps. These operations return a ‘view’ of the original data. 

__c__ Indexing an array with masks, scalar coordinates or other arrays, so that it returns a ‘copy’ of the original data. In the bottom example, an array is indexed with other arrays; this broadcasts the indexing arguments before performing the lookup. 

__d__ Vectorization efficiently applies operations to groups of elements. 

__e__ Broadcasting in the multiplication of two-dimensional arrays. 

__f__ Reduction operations act along one or more axes. In this example, an array is summed along select axes to produce a vector, or along two axes consecutively to produce a scalar. 

__g__ Example NumPy code, illustrating some of these concepts.

So now let's see what we can do with NumPy. NumPy is already installed in most Python environments such as Anaconda, so we don't have to do that ourselves. We only have to tell Python that we want to use NumPy by importing it:

In [1]:
import numpy as np

We gave it a shorter acronym (`np` is arbitrary, but convention). Every we function we want to use from NumPy will have `np.` in front of it, that's why it's useful to make it shorter.

In [2]:
# find out what version of NumPy we have (can be important for troubleshooting)
np.__version__

'1.18.1'

### NumPy arrays
Now we will practice with some useful NumPy functions for arrays.

In [3]:
# create an array from a list
a = np.array([9,0,2,1,0])
print(a)

# find out the datatype
a.dtype

[9 0 2 1 0]


dtype('int64')

In [4]:
# find out the shape
print(a.shape) 

(5,)


In [5]:
# what is the shape
type(a.shape)

tuple

One that you will often use is `np.shape(array_name)`, especially if you are using arrays with a lot of dimensions. The output of `a.shape` is `(5,)`. There being only one number tells you that this array consists of 1 dimensions and that there are 5 entries in this dimension.

In [6]:
# another array with a different datatype and shape
b = np.array([[5,3,1,9],[9,2,3,0]], dtype=np.float64)

b

array([[5., 3., 1., 9.],
       [9., 2., 3., 0.]])

In [7]:
# check dtype and shape
b.dtype, b.shape

(dtype('float64'), (2, 4))

Now we have `b` which has two dimension which each have four entries. You can also think of it as a matrix with 2 rows and 4 columns.

There are several other ways to create $n$-dimensional arrays:

- `np.zeros(n)` = array full of zeros
- `np.ones(n)` = array full of ones
- `np.full(n,value)` = array of full with value `value` 
- `np.ones_like(other_array)` = an array with the same shape as `other_array` but filled with ones
- `np.zeros_like(other_array)` = an array with the same shape as `other_array` but filled with zeroes

Remember that you can also specify the data-type, for example float, integer, strings and complex numbers.

In [8]:
# create some uniform arrays
c = np.zeros((9,9))
d = np.ones((3,6,3), dtype=np.complex128)
e = np.full((3,3), np.pi)
f = np.ones_like(c)
g = np.zeros_like(d)

c,d,e,f,g

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[[1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j]],
 
        [[1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j]],
 
        [[1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 1.+0.j, 1.+0.j],
         [1.+0.j, 

Last week we practiced with `range(start, stop, step)` which gave us a range of number from start to stop (excluding stop itself). In this command you can only use integers. NumPy has different commands to make ranges:

- `np.arange(start, stop, step)` = here `start, stop, step` can be floats, or complex numbers or ... And again, stop itself will not be part of the range (left inclusive, right exclusive)
- `np.linspace(start, stop, number)` = linearly space range of `number` steps, note the difference with `np.arange`
- `np.logspace(start, stop, number)` = same, but now the numbers will be evenly spaced on a logscale, so if you print this array, start wil be `base**start` and stop will be `base**stop`, by default the base is 10, but you change this

In [9]:
a=np.arange(0.2+3j,8.3+9.1j)
b=np.arange(2,4,0.25)
c=np.linspace(2,4,8)
d=np.logspace(1,2,10)

a,b,c,d

(array([0.2+3.j, 1.2+3.j, 2.2+3.j, 3.2+3.j, 4.2+3.j, 5.2+3.j, 6.2+3.j]),
 array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75]),
 array([2.        , 2.28571429, 2.57142857, 2.85714286, 3.14285714,
        3.42857143, 3.71428571, 4.        ]),
 array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
         27.82559402,  35.93813664,  46.41588834,  59.94842503,
         77.42636827, 100.        ]))

You can also create grids using the command `np.meshgrid`. This is very convenient for plotting, for example to plot a certain value over range of coordinates. We will use this later when we move to Matplotlib!

In [10]:
# two dimensional grids
x = np.linspace(-2*np.pi, 2*np.pi, 10)
y = np.linspace(-np.pi, np.pi, 5)
xx, yy = np.meshgrid(x, y)
xx.shape, yy.shape

((5, 10), (5, 10))

### Indexing
The indexing is similar to lists (so zero-based indexing), but you have to be aware of the dimensions of you arrays. For example:

In [11]:
xx # output from np.meshgrid

array([[-6.28318531, -4.88692191, -3.4906585 , -2.0943951 , -0.6981317 ,
         0.6981317 ,  2.0943951 ,  3.4906585 ,  4.88692191,  6.28318531],
       [-6.28318531, -4.88692191, -3.4906585 , -2.0943951 , -0.6981317 ,
         0.6981317 ,  2.0943951 ,  3.4906585 ,  4.88692191,  6.28318531],
       [-6.28318531, -4.88692191, -3.4906585 , -2.0943951 , -0.6981317 ,
         0.6981317 ,  2.0943951 ,  3.4906585 ,  4.88692191,  6.28318531],
       [-6.28318531, -4.88692191, -3.4906585 , -2.0943951 , -0.6981317 ,
         0.6981317 ,  2.0943951 ,  3.4906585 ,  4.88692191,  6.28318531],
       [-6.28318531, -4.88692191, -3.4906585 , -2.0943951 , -0.6981317 ,
         0.6981317 ,  2.0943951 ,  3.4906585 ,  4.88692191,  6.28318531]])

In [12]:
# get some individual elements of xx
xx[0,0], xx[-1,-1], xx[3,-5]

(-6.283185307179586, 6.283185307179586, 0.6981317007977319)

If you want to use the whole column or row, you use `:`, for example the firt row is  `xx[0,:]` . The colon is also used to indicate ranges, for example `xx[x1:x2,y1:y2]`. Keep in mind that this is left inclusive, right exclusive, so `x2` and `y2` will not be part of the selected area.

In [13]:
# get some whole rows and columns
xx[0,:].shape, xx[:,-1].shape

((10,), (5,))

In [14]:
xx[:,-1] 

array([6.28318531, 6.28318531, 6.28318531, 6.28318531, 6.28318531])

In [15]:
# get some ranges, this is again left-inclusive, right-exclusive
print(xx[2:5,3:4].shape)
xx[2:5,3:4]

(3, 1)


array([[-2.0943951],
       [-2.0943951],
       [-2.0943951]])

There are many many advanced ways to index arrays. You can read about them in the manual. Here is one example of a boolean array (= an array of values `True` and `False`, based on the argument `xx<0`)):

In [16]:
# use a boolean array as an index
idx = xx<0
yy[idx]
idx

array([[ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False]])

Sometimes it is necessary to flatten an array, you can do this with the command `ravel`. This is just one example that may be useful later (you don't have to remember all of these commands).

In [17]:
# the array got flattened
print(xx.shape)
print(xx.ravel().shape)

(5, 10)
(50,)


In [18]:
# again, you can always check out the doc string of a function
# to see what it does
help(np.ravel)

Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

## Basic math
The basic Python library is not so big, but NumPy contains a lot of important mathematical functions. There are a huge number of operations available on arrays. All the familiar arithmetic operators are applied on an element-by-element basis. We will discuss a few of them here, these you will probably use a lot, but there is of course a lot more than just this!



In [19]:
np.log(10) # natural logarithm

2.302585092994046

In [20]:
np.log10([1,10,100]) # 10-based logarithm 

array([0., 1., 2.])

In [21]:
f = np.sin(xx) * np.cos(0.5*yy) # sine and cosine
f

array([[ 1.49975978e-32,  6.03020831e-17,  2.09426937e-17,
        -5.30287619e-17, -3.93593894e-17,  3.93593894e-17,
         5.30287619e-17, -2.09426937e-17, -6.03020831e-17,
        -1.49975978e-32],
       [ 1.73191211e-16,  6.96364240e-01,  2.41844763e-01,
        -6.12372436e-01, -4.54519478e-01,  4.54519478e-01,
         6.12372436e-01, -2.41844763e-01, -6.96364240e-01,
        -1.73191211e-16],
       [ 2.44929360e-16,  9.84807753e-01,  3.42020143e-01,
        -8.66025404e-01, -6.42787610e-01,  6.42787610e-01,
         8.66025404e-01, -3.42020143e-01, -9.84807753e-01,
        -2.44929360e-16],
       [ 1.73191211e-16,  6.96364240e-01,  2.41844763e-01,
        -6.12372436e-01, -4.54519478e-01,  4.54519478e-01,
         6.12372436e-01, -2.41844763e-01, -6.96364240e-01,
        -1.73191211e-16],
       [ 1.49975978e-32,  6.03020831e-17,  2.09426937e-17,
        -5.30287619e-17, -3.93593894e-17,  3.93593894e-17,
         5.30287619e-17, -2.09426937e-17, -6.03020831e-17,
        -1.

In [22]:
np.exp(1) # the number e

2.718281828459045

In [23]:
np.pi # the number pi

3.141592653589793

## Broadcasting ##

__Broadcasting__ = how NumPy treats arrays with different shapes during arithmetic operations  (part (e) in the NumPy figure above). It "broadcasts" smaller arrays across the larger arrays so they have compatible shapes to do computations; an example of this is shown in the figure below. You can do matrix operations by vectorizing array operations instead of using `for`-`while`-`if`-loops. These loops use a lot of data/memory and using broadcasting can make your code a lot faster and more efficient. It is very similar to doing operations to matrices, such as multiplication.

<img src="http://scipy-lectures.github.io/_images/numpy_broadcasting.png" width="600">

Usually, NumPy operations are done on pairs of arrays on an element-by-element basis.  So, when operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

- they are equal, or

- one of them is 1

If these conditions are not met, `a ValueError: operands could not be broadcast together` exception is thrown, indicating that the arrays have incompatible shapes. 

Some examples of broadcasting are given below:

In [24]:
# add f and x  (this is the second row example in the figure above)
print(f.shape, x.shape)
d = f + x
print(d.shape)

(5, 10) (10,)
(5, 10)


In [25]:
# multiply f by x
print(f.shape, x.shape)
g = f * x
print(g.shape)

(5, 10) (10,)
(5, 10)


In [26]:
# multiply f by y
# why does this not work?
print(f.shape, y.shape)
h = f * y
print(h.shape)

(5, 10) (5,)


ValueError: operands could not be broadcast together with shapes (5,10) (5,) 

In [27]:
# multiply f by y
# why does this work?
print(f.shape, y.shape)
h = np.transpose(f) * y
print(h.shape)

(5, 10) (5,)
(10, 5)


To show you that these kinds of vectorized computations are indeed faster than loops, we will compare the same computation with a loop. With the command `%timeit`, Python tells you how long this computation takes.

In [28]:
# Vectorized
def sum_vect(a,b):
    c = a + b
    return c

# Double for-loop
def sum_loop(a,b):
    c = np.zeros(a.shape)
    for i in range(len(a[:,0])-1):
        for j in range(len(a[0,:])-1):
            c[i,j] = a[i,j]+b[i]
    return c

In [29]:
# run-time of the for-loop
d_comp = sum_loop(f,x)

%timeit sum_loop(f,x)

20.3 µs ± 655 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [30]:
# run-time of the vectorized
%timeit sum_vect(f,x)

1.37 µs ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [31]:
%%time

dus = np.sin(2*np.pi)
# another useful (cell)magic command is `%%time` 
# on an otherwise empty first line
# to time the execution of a cell

CPU times: user 21 µs, sys: 1 µs, total: 22 µs
Wall time: 25 µs


## Reduction Operation
These operation collapse one or more dimensions by performing an operation, for example, summing over an axis or even all axes.
(part _f_ of the array operations figure above)
If the array has multiple dimensions, you can choose over which dimension to perform the operation.

In [32]:
g

array([[-9.42326863e-32, -2.94691571e-16, -7.31037918e-17,
         1.11063179e-16,  2.74780375e-17,  2.74780375e-17,
         1.11063179e-16, -7.31037918e-17, -2.94691571e-16,
        -9.42326863e-32],
       [-1.08819247e-15, -3.40307766e+00, -8.44197477e-01,
         1.28254983e+00,  3.17314456e-01,  3.17314456e-01,
         1.28254983e+00, -8.44197477e-01, -3.40307766e+00,
        -1.08819247e-15],
       [-1.53893655e-15, -4.81267858e+00, -1.19387552e+00,
         1.81379936e+00,  4.48750407e-01,  4.48750407e-01,
         1.81379936e+00, -1.19387552e+00, -4.81267858e+00,
        -1.53893655e-15],
       [-1.08819247e-15, -3.40307766e+00, -8.44197477e-01,
         1.28254983e+00,  3.17314456e-01,  3.17314456e-01,
         1.28254983e+00, -8.44197477e-01, -3.40307766e+00,
        -1.08819247e-15],
       [-9.42326863e-32, -2.94691571e-16, -7.31037918e-17,
         1.11063179e-16,  2.74780375e-17,  2.74780375e-17,
         1.11063179e-16, -7.31037918e-17, -2.94691571e-16,
        -9.

In [33]:
# shape
g.shape

(5, 10)

In [34]:
# sum
g.sum()

-18.077652068817933

In [35]:
# mean
g.mean()

-0.3615530413763587

In [36]:
# standard deviation
g.std()

1.4544951406053706

In [37]:
# max
g.max()

1.813799364234218

In [38]:
# min
g.min()

-4.812678580984438

In [40]:
# apply on just one axis
g_ymean = g.mean(axis=0)
g_xmean = g.mean(axis=1)
g_ymean, g_xmean

(array([-7.43064301e-16, -2.32376678e+00, -5.76454095e-01,  8.75779805e-01,
         2.16675864e-01,  2.16675864e-01,  8.75779805e-01, -5.76454095e-01,
        -2.32376678e+00, -7.43064301e-16]),
 array([-4.58508292e-17, -5.29482170e-01, -7.48800866e-01, -5.29482170e-01,
        -4.58508292e-17]))

## <span style="color:blue">Exercises</span>
1. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives. Subsequently create a 3x10 array from them. Ultimately compute the sum column-wise (over axis 0).

2. Create an array of length `N=12` equally spaced between -5 and (including) 3, then compute the square of these values. 

3. Create a 2D grid of longitudes $\lambda\in[0^\circ,360^\circ]$ and latitudes $\varphi\in[-90^\circ,90^\circ]$ every $30^\circ$. Then calculate $\sin(30^\circ)$ and $\cos(\pi)$, i.e. find out how to use degrees and radians with numpy functions.

4. Create an array of `N=500` samples of the Normal distribution of mean=3, standard deviation=2. Determine the mean and standard deviation with numpy functions.

5. _Hard:_ Compute an approximation to $\pi$ using Monte Carlo sampling. Use only the `numpy.random.uniform()` function. These hints may help:
- The area of a circle is $area = \pi \times radius^2$
- Sample the unit square $(0,1)\times(0,1)$ with $N$ uniformly in $x$ and $y$ distributed points.

## <span style="color:green">(possible) Solutions</span>

In [41]:
# 1. Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.
# Subsequently create a 3x10 array from them.
# Ultimately compute the sum column-wise (over axis 0).
x_0 = np.zeros(10)
x_1 = np.ones(10)
x_5 = x_1*5

combined = np.array([x_0,x_1,x_5])
print(combined.shape)
print(combined)
sum_column = combined.sum(axis=0)
sum_column

(3, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [42]:
# 2. Create an array of length N=12 equally spaced between -5 and (including) 3, 
# then compute the square of these values. 

y_array = np.linspace(-5,3,12)
y_square = y_array**2
y_square

array([2.50000000e+01, 1.82561983e+01, 1.25702479e+01, 7.94214876e+00,
       4.37190083e+00, 1.85950413e+00, 4.04958678e-01, 8.26446281e-03,
       6.69421488e-01, 2.38842975e+00, 5.16528926e+00, 9.00000000e+00])

In [43]:
# 3. Create a 2D grid of longitudes lambda [0,360] deg and latitudes phi [-90,90] every 30 degrees.

d_deg = 30 # stepsize
lon = np.arange(0,361,d_deg)
lat = np.arange(-90,91,d_deg)

# Then calculate sin(30) and cos(pi), i.e. find out how to use degrees and radians with numpy functions.
print(np.sin(30))              # this is wrong
print(np.sin(np.deg2rad(30)))  # this is correct
print(np.sin(30*np.pi/180))              # this is also correct
# --> numpy trigonometric functions want radians, not degrees
print(np.cos(np.pi))

-0.9880316240928618
0.49999999999999994
0.49999999999999994
-1.0


In [44]:
# 4. Create an array of `N=[500,1200,1e5]` samples of the Normal
# distribution of mean=3, standard deviation=2.
# Determine the mean and standard deviation with numpy functions.

for N in [500,1200,int(1e5)]:
    D = np.random.normal(loc=3, scale=2, size=N)
    print(f'N = {N:6d}, mean = {D.mean():.2f}, std = {D.std()}')
    
# again, the numbers and letters after the colon in the f-string 
# determine the output format

N =    500, mean = 3.17, std = 2.0074264924287384
N =   1200, mean = 3.05, std = 2.0479942278879704
N = 100000, mean = 3.00, std = 1.998493491003647
